### ISSUE TITLE
코드상의 디렉토리와 레포지토리 디렉토리 안 맞음

### ISSUE THREAD

**Issue by sohds** [sohds/P4DS_gaeun_allocation#13]
각자 로컬에서 돌리고 GitHub 레포지토리에 올렸기 때문에, 레포지토리 디렉토리와 코드상의 디렉토리가 안 맞음

* dataprep (서진, 유빈)
* visualization (서진, 유빈)
* model (서연)

**Comment by jinnypstar** [comment]
- dataprep/concat_climate.ipynb
    - 초반 dataframe 불러오는 과정에서 레포지토리 디렉토리와 코드 디렉토리가 상이함
    - 엑셀 저장한 파일명이 다름 (’final_for_regression.xlsx → ‘../resource/final_for_models.xlsx’로 변경)
- dataprep/dayoftheweek_add.ipynb
    - 여기도 데이터프레임 불러오는 과정과 엑셀 저장한 파일 디렉토리 상이함 체크 부탁
    - ‘230211_1hour_data.xlsx’ 파일 안 올라감 → resource에 올리기
- dataprep/merge_menu_sum.ipynb
    - 디렉토리 안 맞음
- visualization/bargraph_menu.ipynb
    - ‘only_menu.xlsx’ 파일 resource에 올리기
    - only_menu.xlsx → ‘../resource/only_menu.xlsx’로 변경

**Comment by sohds** [comment]
* model/cross_reg_2nd.ipynb
* model/cross_reg_both.ipynb
  * 두 파일 모두 OLS summary 추출 당시 디렉토리 제대로 지정하지 않았음, resource에 수정!

**Comment by sohds** [comment]
![Uploading image.png…]()
commit 업로드 시 이렇게 부탁합니다~!

**Comment by sohds** [comment]
세 명 담당했던 코드 디렉토리 이상건 모두 처리 완료.
